import { Separator } from "./ui/separator";


export const BubbleMessage = ({message,id,isUser}: { message: string,id:number,isUser:boolean }) => {

    //This function is used to filter and the clear the text that is generated by the AI so it can be clear and easy to read for the user
    function cleanText(input: string): string {

        const cleaned = input
            // Convert markdown italics to <em>
            .replace(/\*([^*]+)\*/g, '<em>$1</em>')
            //convert the Hash + to subtitles
            .replace(/##+ (.+)/g, '<strong>$1</strong>')
            // Convert markdown bold to <strong>
            .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
            // Convert numbered lists
            .replace(/(\d+\.\s+)(.+)/g, '<li>$2</li>')
            // Convert dashed lists
            .replace(/-\s+(.+)/g, '<li>$1</li>')
            .replace(/<\/?em>/g, '')
            .replace(/<\/li>/g, '\n')// Remove <li> and </li> tags
            .replace(/<li>/g, '**')
            .replace(/\*+/g, '');
            // Preserve paragraphs
            //.replace(/\n\n/g, '</p><p>')
            // Convert single newlines to line breaks
            //.replace(/\n/g, '<br/>');


            return cleaned;
    }

    const formattedHTML = cleanText(message);
    return (
 
            <p key={id} className={`text-unwrap w-full ${isUser ? 'text-right ' : 'text-left'}`}>{isUser ? message : formattedHTML}
              
            </p>
            
       
    )
}